// Layout Registry
// Maps section types to their available layout variants

export const LAYOUT_REGISTRY = {
  navbar: [
    { id: 'navbar-01', name: 'Lumière — Floating Glass Pill', component: 'Navbar01', thumbnail: null },
    { id: 'navbar-02', name: 'Noir — Full Dark Luxury', component: 'Navbar02', thumbnail: null },
    { id: 'navbar-03', name: 'Aurora — Gradient Border Glow', component: 'Navbar03', thumbnail: null },
    { id: 'navbar-04', name: 'Emerald — Split Announcement', component: 'Navbar04', thumbnail: null },
    { id: 'navbar-05', name: 'Veloce — Sporty Mega-Bar', component: 'Navbar05', thumbnail: null },
    { id: 'navbar-06', name: 'Sakura — Centered Elegant', component: 'Navbar06', thumbnail: null },
    { id: 'navbar-07', name: 'Obsidian — Scroll Morph', component: 'Navbar07', thumbnail: null },
    { id: 'navbar-08', name: 'Papercut — Brutalist Bold', component: 'Navbar08', thumbnail: null },
    { id: 'navbar-09', name: 'Serenity — Minimal Zen', component: 'Navbar09', thumbnail: null },
    { id: 'navbar-10', name: 'Nebula — Glassmorphism Space', component: 'Navbar10', thumbnail: null },
    { id: 'navbar-11', name: 'Monocle — Editorial Serif', component: 'Navbar11', thumbnail: null },
    { id: 'navbar-12', name: 'Terminal — Developer Dark', component: 'Navbar12', thumbnail: null },
    { id: 'navbar-13', name: 'Solstice — Floating Dock', component: 'Navbar13', thumbnail: null },
    { id: 'navbar-14', name: 'Maison Double — Double Row', component: 'Navbar14', thumbnail: null },
    { id: 'navbar-15', name: 'Iris — Sidebar Drawer', component: 'Navbar15', thumbnail: null },
    { id: 'navbar-16', name: 'Goldleaf — Gold Foil Premium', component: 'Navbar16', thumbnail: null },
    { id: 'navbar-17', name: 'Pulse — Search Command Bar', component: 'Navbar17', thumbnail: null },
    { id: 'navbar-18', name: 'Transgo — Logistics Pro', component: 'Navbar18', thumbnail: null },
    { id: 'navbar-19', name: 'Kioso — Rounded Playful', component: 'Navbar19', thumbnail: null },
    { id: 'navbar-20', name: 'Aether — Ultra Premium Finale', component: 'Navbar20', thumbnail: null },
  ],
  hero: [
    { id: 'hero-01', name: 'Aurora — Centered Gradient Glow', component: 'Hero01', thumbnail: null },
    { id: 'hero-02', name: 'Noir — Full Dark Cinematic', component: 'Hero02', thumbnail: null },
    { id: 'hero-03', name: 'Transgo — Logistics Split', component: 'Hero03', thumbnail: null },
    { id: 'hero-04', name: 'Papercut — Brutalist Statement', component: 'Hero04', thumbnail: null },
    { id: 'hero-05', name: 'Serenity — Minimal Zen', component: 'Hero05', thumbnail: null },
    { id: 'hero-06', name: 'Nebula — Glass Space Stats', component: 'Hero06', thumbnail: null },
    { id: 'hero-07', name: 'Terminal — Developer Command', component: 'Hero07', thumbnail: null },
    { id: 'hero-08', name: 'Sakura — Centered Floral', component: 'Hero08', thumbnail: null },
    { id: 'hero-09', name: 'Goldleaf — Heritage Gold', component: 'Hero09', thumbnail: null },
    { id: 'hero-10', name: 'Pulse — Search-First Marketplace', component: 'Hero10', thumbnail: null },
    { id: 'hero-11', name: 'Iris — Gradient Mesh Playground', component: 'Hero11', thumbnail: null },
    { id: 'hero-12', name: 'Obsidian — Dark Split Enterprise', component: 'Hero12', thumbnail: null },
    { id: 'hero-13', name: 'Kioso — Playful Food Hero', component: 'Hero13', thumbnail: null },
    { id: 'hero-14', name: 'Maison — Corporate Trust', component: 'Hero14', thumbnail: null },
    { id: 'hero-15', name: 'Monocle — Editorial Magazine', component: 'Hero15', thumbnail: null },
    { id: 'hero-16', name: 'Emerald — Eco Shop Hero', component: 'Hero16', thumbnail: null },
    { id: 'hero-17', name: 'Veloce — Sport Full-Bleed', component: 'Hero17', thumbnail: null },
    { id: 'hero-18', name: 'Solstice — App Download', component: 'Hero18', thumbnail: null },
    { id: 'hero-19', name: 'Lumière — Agency Portfolio', component: 'Hero19', thumbnail: null },
    { id: 'hero-20', name: 'Aether — Ultra Premium Finale', component: 'Hero20', thumbnail: null },
  ],
  about: [
    { id: 'about-01', name: 'Lumière — Floating Glass Story', component: 'About01', thumbnail: null },
    { id: 'about-02', name: 'Noir — Full Dark Luxury Story', component: 'About02', thumbnail: null },
    { id: 'about-03', name: 'Aurora — Centered Gradient Story', component: 'About03', thumbnail: null },
    { id: 'about-04', name: 'Emerald — Eco Impact Story', component: 'About04', thumbnail: null },
    { id: 'about-05', name: 'Veloce — Sporty Garage Story', component: 'About05', thumbnail: null },
    { id: 'about-06', name: 'Sakura — Centered Floral Story', component: 'About06', thumbnail: null },
    { id: 'about-07', name: 'Obsidian — Enterprise Dark Story', component: 'About07', thumbnail: null },
    { id: 'about-08', name: 'Papercut — Brutalist Manifesto', component: 'About08', thumbnail: null },
    { id: 'about-09', name: 'Serenity — Minimal Zen Story', component: 'About09', thumbnail: null },
    { id: 'about-10', name: 'Nebula — Glass Space Story', component: 'About10', thumbnail: null },
    { id: 'about-11', name: 'Terminal — Developer Story', component: 'About11', thumbnail: null },
    { id: 'about-12', name: 'Iris — Gradient Mesh Story', component: 'About12', thumbnail: null },
    { id: 'about-13', name: 'Kioso — Playful Kitchen Story', component: 'About13', thumbnail: null },
    { id: 'about-14', name: 'Maison — Corporate Trust Story', component: 'About14', thumbnail: null },
    { id: 'about-15', name: 'Monocle — Editorial Newsroom', component: 'About15', thumbnail: null },
    { id: 'about-16', name: 'Pulse — Marketplace Stats Story', component: 'About16', thumbnail: null },
    { id: 'about-17', name: 'Transgo — Fleet Heritage Story', component: 'About17', thumbnail: null },
    { id: 'about-18', name: 'Solstice — Fintech App Story', component: 'About18', thumbnail: null },
    { id: 'about-19', name: 'Goldleaf — Heritage Craft Story', component: 'About19', thumbnail: null },
    { id: 'about-20', name: 'Aether — Ultra Premium Finale', component: 'About20', thumbnail: null },
  ],
  services: [
    { id: 'services-01', name: 'Aurora — Centered Gradient Glow Services', component: 'Services01', thumbnail: null },
    { id: 'services-02', name: 'Noir — Full Dark Cinematic Services', component: 'Services02', thumbnail: null },
    { id: 'services-03', name: 'Transgo — Logistics Split Services', component: 'Services03', thumbnail: null },
    { id: 'services-04', name: 'Papercut — Brutalist Statement Services', component: 'Services04', thumbnail: null },
    { id: 'services-05', name: 'Serenity — Minimal Zen Services', component: 'Services05', thumbnail: null },
    { id: 'services-06', name: 'Nebula — Glass Space Stats Services', component: 'Services06', thumbnail: null },
    { id: 'services-07', name: 'Terminal — Developer Command Services', component: 'Services07', thumbnail: null },
    { id: 'services-08', name: 'Sakura — Centered Floral Services', component: 'Services08', thumbnail: null },
    { id: 'services-09', name: 'Goldleaf — Heritage Gold Services', component: 'Services09', thumbnail: null },
    { id: 'services-10', name: 'Pulse — Search-First Marketplace Services', component: 'Services10', thumbnail: null },
    { id: 'services-11', name: 'Iris — Gradient Mesh Playground Services', component: 'Services11', thumbnail: null },
    { id: 'services-12', name: 'Obsidian — Dark Split Enterprise Services', component: 'Services12', thumbnail: null },
    { id: 'services-13', name: 'Kioso — Playful Food Services', component: 'Services13', thumbnail: null },
    { id: 'services-14', name: 'Maison — Corporate Trust Services', component: 'Services14', thumbnail: null },
    { id: 'services-15', name: 'Monocle — Editorial Magazine Services', component: 'Services15', thumbnail: null },
    { id: 'services-16', name: 'Emerald — Eco Shop Services', component: 'Services16', thumbnail: null },
    { id: 'services-17', name: 'Veloce — Sport Full-Bleed Services', component: 'Services17', thumbnail: null },
    { id: 'services-18', name: 'Solstice — App Download Services', component: 'Services18', thumbnail: null },
    { id: 'services-19', name: 'Lumière — Agency Portfolio Services', component: 'Services19', thumbnail: null },
    { id: 'services-20', name: 'Aether — Ultra Premium Finale Services', component: 'Services20', thumbnail: null },
  ],
  gallery: [
    { id: 'gallery-01', name: 'Aurora — Centered Gradient Glow', component: 'Gallery01', thumbnail: null },
    { id: 'gallery-02', name: 'Noir — Full Dark Cinematic', component: 'Gallery02', thumbnail: null },
    { id: 'gallery-03', name: 'Transgo — Logistics Split', component: 'Gallery03', thumbnail: null },
    { id: 'gallery-04', name: 'Papercut — Brutalist Statement', component: 'Gallery04', thumbnail: null },
    { id: 'gallery-05', name: 'Serenity — Minimal Zen', component: 'Gallery05', thumbnail: null },
    { id: 'gallery-06', name: 'Nebula — Glass Space Stats', component: 'Gallery06', thumbnail: null },
    { id: 'gallery-07', name: 'Terminal — Developer Command', component: 'Gallery07', thumbnail: null },
    { id: 'gallery-08', name: 'Sakura — Centered Floral', component: 'Gallery08', thumbnail: null },
    { id: 'gallery-09', name: 'Goldleaf — Heritage Gold', component: 'Gallery09', thumbnail: null },
    { id: 'gallery-10', name: 'Pulse — Search-First Marketplace', component: 'Gallery10', thumbnail: null },
    { id: 'gallery-11', name: 'Iris — Gradient Mesh Playground', component: 'Gallery11', thumbnail: null },
    { id: 'gallery-12', name: 'Obsidian — Dark Split Enterprise', component: 'Gallery12', thumbnail: null },
    { id: 'gallery-13', name: 'Kioso — Playful Food', component: 'Gallery13', thumbnail: null },
    { id: 'gallery-14', name: 'Maison — Corporate Trust', component: 'Gallery14', thumbnail: null },
    { id: 'gallery-15', name: 'Monocle — Editorial Magazine', component: 'Gallery15', thumbnail: null },
    { id: 'gallery-16', name: 'Emerald — Eco Shop', component: 'Gallery16', thumbnail: null },
    { id: 'gallery-17', name: 'Veloce — Sport Full-Bleed', component: 'Gallery17', thumbnail: null },
    { id: 'gallery-18', name: 'Solstice — App Download', component: 'Gallery18', thumbnail: null },
    { id: 'gallery-19', name: 'Lumière — Agency Portfolio', component: 'Gallery19', thumbnail: null },
    { id: 'gallery-20', name: 'Aether — Ultra Premium Finale', component: 'Gallery20', thumbnail: null },
  ],
  contact: [
    { id: 'contact-01', name: 'Aurora — Centered Gradient Glow', component: 'Contact01', thumbnail: null },
    { id: 'contact-02', name: 'Noir — Full Dark Cinematic', component: 'Contact02', thumbnail: null },
    { id: 'contact-03', name: 'Transgo — Logistics Split', component: 'Contact03', thumbnail: null },
    { id: 'contact-04', name: 'Papercut — Brutalist Statement', component: 'Contact04', thumbnail: null },
    { id: 'contact-05', name: 'Serenity — Minimal Zen', component: 'Contact05', thumbnail: null },
    { id: 'contact-06', name: 'Nebula — Glass Space Stats', component: 'Contact06', thumbnail: null },
    { id: 'contact-07', name: 'Terminal — Developer Command', component: 'Contact07', thumbnail: null },
    { id: 'contact-08', name: 'Sakura — Centered Floral', component: 'Contact08', thumbnail: null },
    { id: 'contact-09', name: 'Goldleaf — Heritage Gold', component: 'Contact09', thumbnail: null },
    { id: 'contact-10', name: 'Pulse — Search-First Marketplace', component: 'Contact10', thumbnail: null },
    { id: 'contact-11', name: 'Iris — Gradient Mesh Playground', component: 'Contact11', thumbnail: null },
    { id: 'contact-12', name: 'Obsidian — Dark Split Enterprise', component: 'Contact12', thumbnail: null },
    { id: 'contact-13', name: 'Kioso — Playful Food', component: 'Contact13', thumbnail: null },
    { id: 'contact-14', name: 'Maison — Corporate Trust', component: 'Contact14', thumbnail: null },
    { id: 'contact-15', name: 'Monocle — Editorial Magazine', component: 'Contact15', thumbnail: null },
    { id: 'contact-16', name: 'Emerald — Eco Shop', component: 'Contact16', thumbnail: null },
    { id: 'contact-17', name: 'Veloce — Sport Full-Bleed', component: 'Contact17', thumbnail: null },
    { id: 'contact-18', name: 'Solstice — App Download', component: 'Contact18', thumbnail: null },
    { id: 'contact-19', name: 'Lumière — Agency Portfolio', component: 'Contact19', thumbnail: null },
    { id: 'contact-20', name: 'Aether — Ultra Premium Finale', component: 'Contact20', thumbnail: null },
  ],
  footer: [
    { id: 'footer-01', name: 'Lumière — Floating Glass Footer', component: 'Footer01', thumbnail: null },
    { id: 'footer-02', name: 'Noir — Full Dark Luxury', component: 'Footer02', thumbnail: null },
    { id: 'footer-03', name: 'Aurora — Gradient Glow', component: 'Footer03', thumbnail: null },
    { id: 'footer-04', name: 'Emerald — Eco Newsletter', component: 'Footer04', thumbnail: null },
    { id: 'footer-05', name: 'Veloce — Sporty Strip', component: 'Footer05', thumbnail: null },
    { id: 'footer-06', name: 'Sakura — Centered Floral', component: 'Footer06', thumbnail: null },
    { id: 'footer-07', name: 'Obsidian — Enterprise Dark', component: 'Footer07', thumbnail: null },
    { id: 'footer-08', name: 'Papercut — Brutalist Bold', component: 'Footer08', thumbnail: null },
    { id: 'footer-09', name: 'Serenity — Minimal Zen', component: 'Footer09', thumbnail: null },
    { id: 'footer-10', name: 'Nebula — Glass Space', component: 'Footer10', thumbnail: null },
    { id: 'footer-11', name: 'Monocle — Editorial Serif', component: 'Footer11', thumbnail: null },
    { id: 'footer-12', name: 'Terminal — Developer Dark', component: 'Footer12', thumbnail: null },
    { id: 'footer-13', name: 'Solstice — App Download', component: 'Footer13', thumbnail: null },
    { id: 'footer-14', name: 'Maison Double — Institutional', component: 'Footer14', thumbnail: null },
    { id: 'footer-15', name: 'Iris — Gradient Mesh', component: 'Footer15', thumbnail: null },
    { id: 'footer-16', name: 'Goldleaf — Gold Foil Premium', component: 'Footer16', thumbnail: null },
    { id: 'footer-17', name: 'Pulse — Marketplace Command', component: 'Footer17', thumbnail: null },
    { id: 'footer-18', name: 'Transgo — Logistics Pro', component: 'Footer18', thumbnail: null },
    { id: 'footer-19', name: 'Kioso — Rounded Playful', component: 'Footer19', thumbnail: null },
    { id: 'footer-20', name: 'Aether — Ultra Premium Finale', component: 'Footer20', thumbnail: null },
  ],
  statistics: [
    { id: 'statistics-01', name: 'Aurora — Centered Gradient Glow', component: 'Statistics01', thumbnail: null },
    { id: 'statistics-02', name: 'Noir — Full Dark Cinematic', component: 'Statistics02', thumbnail: null },
    { id: 'statistics-03', name: 'Transgo — Logistics Split', component: 'Statistics03', thumbnail: null },
    { id: 'statistics-04', name: 'Papercut — Brutalist Statement', component: 'Statistics04', thumbnail: null },
    { id: 'statistics-05', name: 'Serenity — Minimal Zen', component: 'Statistics05', thumbnail: null },
    { id: 'statistics-06', name: 'Nebula — Glass Space Stats', component: 'Statistics06', thumbnail: null },
    { id: 'statistics-07', name: 'Terminal — Developer Command', component: 'Statistics07', thumbnail: null },
    { id: 'statistics-08', name: 'Sakura — Centered Floral', component: 'Statistics08', thumbnail: null },
    { id: 'statistics-09', name: 'Goldleaf — Heritage Gold', component: 'Statistics09', thumbnail: null },
    { id: 'statistics-10', name: 'Pulse — Search-First Marketplace', component: 'Statistics10', thumbnail: null },
    { id: 'statistics-11', name: 'Iris — Gradient Mesh Playground', component: 'Statistics11', thumbnail: null },
    { id: 'statistics-12', name: 'Obsidian — Dark Split Enterprise', component: 'Statistics12', thumbnail: null },
    { id: 'statistics-13', name: 'Kioso — Playful Food Stats', component: 'Statistics13', thumbnail: null },
    { id: 'statistics-14', name: 'Maison — Corporate Trust', component: 'Statistics14', thumbnail: null },
    { id: 'statistics-15', name: 'Monocle — Editorial Magazine', component: 'Statistics15', thumbnail: null },
    { id: 'statistics-16', name: 'Emerald — Eco Impact Stats', component: 'Statistics16', thumbnail: null },
    { id: 'statistics-17', name: 'Veloce — Sport Full-Bleed', component: 'Statistics17', thumbnail: null },
    { id: 'statistics-18', name: 'Solstice — App Download', component: 'Statistics18', thumbnail: null },
    { id: 'statistics-19', name: 'Lumière — Agency Portfolio', component: 'Statistics19', thumbnail: null },
    { id: 'statistics-20', name: 'Aether — Ultra Premium Finale', component: 'Statistics20', thumbnail: null },
  ],
  fleet: [
    { id: 'fleet-01', name: 'Aurora - Centered Card Grid', component: 'Fleet01', thumbnail: null },
    { id: 'fleet-02', name: 'Noir - Dark Split Image', component: 'Fleet02', thumbnail: null },
    { id: 'fleet-03', name: 'Veloce - Cinematic Full Dark', component: 'Fleet03', thumbnail: null },
    { id: 'fleet-04', name: 'Papercut - Neo-Brutalist Stats', component: 'Fleet04', thumbnail: null },
    { id: 'fleet-05', name: 'Serenity - Minimal Clean Grid', component: 'Fleet05', thumbnail: null },
    { id: 'fleet-06', name: 'Nebula - Dark Glass Dashboard', component: 'Fleet06', thumbnail: null },
    { id: 'fleet-07', name: 'Terminal - Developer Monitor', component: 'Fleet07', thumbnail: null },
    { id: 'fleet-08', name: 'Sakura - Warm Gradient Bento', component: 'Fleet08', thumbnail: null },
    { id: 'fleet-09', name: 'Summit - Navy Corporate Split', component: 'Fleet09', thumbnail: null },
    { id: 'fleet-10', name: 'Pulse - Interactive Filter Tabs', component: 'Fleet10', thumbnail: null },
    { id: 'fleet-11', name: 'Verdant - Eco Green Fleet', component: 'Fleet11', thumbnail: null },
    { id: 'fleet-12', name: 'Solstice - Orange Full-Bleed', component: 'Fleet12', thumbnail: null },
    { id: 'fleet-13', name: 'Monocle - Editorial Spec Table', component: 'Fleet13', thumbnail: null },
    { id: 'fleet-14', name: 'Zephyr - Glassmorphism AI Fleet', component: 'Fleet14', thumbnail: null },
    { id: 'fleet-15', name: 'Meridian - Timeline Heritage', component: 'Fleet15', thumbnail: null },
    { id: 'fleet-16', name: 'Lumiere - Agency Portfolio', component: 'Fleet16', thumbnail: null },
    { id: 'fleet-17', name: 'Transgo - Full-Width Banner', component: 'Fleet17', thumbnail: null },
    { id: 'fleet-18', name: 'Solaris - App Download CTA', component: 'Fleet18', thumbnail: null },
    { id: 'fleet-19', name: 'Orion - Split Feature List', component: 'Fleet19', thumbnail: null },
    { id: 'fleet-20', name: 'Aether - Ultra Premium Finale', component: 'Fleet20', thumbnail: null },
  ],
  coverage: [
    { id: 'coverage-01', name: 'Aurora - Centered Region Card Grid', component: 'Coverage01', thumbnail: null },
    { id: 'coverage-02', name: 'Noir - Dark Interactive Network Map', component: 'Coverage02', thumbnail: null },
    { id: 'coverage-03', name: 'Veloce - Dark Cinematic Route Hub', component: 'Coverage03', thumbnail: null },
    { id: 'coverage-04', name: 'Papercut - Neo-Brutalist Geo Coverage', component: 'Coverage04', thumbnail: null },
    { id: 'coverage-05', name: 'Serenity - Minimal Clean Area Grid', component: 'Coverage05', thumbnail: null },
    { id: 'coverage-06', name: 'Nebula - Dark Glass Radar Dashboard', component: 'Coverage06', thumbnail: null },
    { id: 'coverage-07', name: 'Terminal - Developer Geo Node Monitor', component: 'Coverage07', thumbnail: null },
    { id: 'coverage-08', name: 'Sakura - Warm Gradient Bento Zones', component: 'Coverage08', thumbnail: null },
    { id: 'coverage-09', name: 'Summit - Navy Corporate Logistics Grid', component: 'Coverage09', thumbnail: null },
    { id: 'coverage-10', name: 'Pulse - Interactive Region Filter Tabs', component: 'Coverage10', thumbnail: null },
    { id: 'coverage-11', name: 'Verdant - Eco Green Distribution Network', component: 'Coverage11', thumbnail: null },
    { id: 'coverage-12', name: 'Solstice - Sunset Express Corridor', component: 'Coverage12', thumbnail: null },
    { id: 'coverage-13', name: 'Monocle - Editorial Delivery Spec Matrix', component: 'Coverage13', thumbnail: null },
    { id: 'coverage-14', name: 'Zephyr - Glassmorphism AI Network Hub', component: 'Coverage14', thumbnail: null },
    { id: 'coverage-15', name: 'Meridian - National Expansion Milestones', component: 'Coverage15', thumbnail: null },
    { id: 'coverage-16', name: 'Lumiere - Luxury Global Ports Showcase', component: 'Coverage16', thumbnail: null },
    { id: 'coverage-17', name: 'Transgo - Nationwide Highway Freight Map', component: 'Coverage17', thumbnail: null },
    { id: 'coverage-18', name: 'Solaris - App Postal Code Lookup CTA', component: 'Coverage18', thumbnail: null },
    { id: 'coverage-19', name: 'Orion - Split Hub & Warehouses List', component: 'Coverage19', thumbnail: null },
    { id: 'coverage-20', name: 'Aether - Ultra Premium Global Network Finale', component: 'Coverage20', thumbnail: null },
  ],
  testimonials: [
    { id: 'testimonials-01', name: 'Testimonials 01', component: 'Testimonials01', thumbnail: null },
  ],
  clients: [
    { id: 'clients-01', name: 'Aurora — Centered Gradient Glow', component: 'Clients01', thumbnail: null },
    { id: 'clients-02', name: 'Noir — Full Dark Cinematic', component: 'Clients02', thumbnail: null },
    { id: 'clients-03', name: 'Transgo — Logistics Split', component: 'Clients03', thumbnail: null },
    { id: 'clients-04', name: 'Papercut — Brutalist Statement', component: 'Clients04', thumbnail: null },
    { id: 'clients-05', name: 'Serenity — Minimal Zen', component: 'Clients05', thumbnail: null },
    { id: 'clients-06', name: 'Nebula — Glass Space Stats', component: 'Clients06', thumbnail: null },
    { id: 'clients-07', name: 'Terminal — Developer Command', component: 'Clients07', thumbnail: null },
    { id: 'clients-08', name: 'Sakura — Centered Floral', component: 'Clients08', thumbnail: null },
    { id: 'clients-09', name: 'Goldleaf — Heritage Gold', component: 'Clients09', thumbnail: null },
    { id: 'clients-10', name: 'Pulse — Search-First Marketplace', component: 'Clients10', thumbnail: null },
    { id: 'clients-11', name: 'Iris — Gradient Mesh Playground', component: 'Clients11', thumbnail: null },
    { id: 'clients-12', name: 'Obsidian — Dark Split Enterprise', component: 'Clients12', thumbnail: null },
    { id: 'clients-13', name: 'Kioso — Playful Food', component: 'Clients13', thumbnail: null },
    { id: 'clients-14', name: 'Maison — Corporate Trust', component: 'Clients14', thumbnail: null },
    { id: 'clients-15', name: 'Monocle — Editorial Magazine', component: 'Clients15', thumbnail: null },
    { id: 'clients-16', name: 'Emerald — Eco Shop', component: 'Clients16', thumbnail: null },
    { id: 'clients-17', name: 'Veloce — Sport Full-Bleed', component: 'Clients17', thumbnail: null },
    { id: 'clients-18', name: 'Solstice — App Download', component: 'Clients18', thumbnail: null },
    { id: 'clients-19', name: 'Lumière — Agency Portfolio', component: 'Clients19', thumbnail: null },
    { id: 'clients-20', name: 'Aether — Ultra Premium Finale', component: 'Clients20', thumbnail: null },
  ],
  programs: [
    { id: 'programs-01', name: 'Programs 01', component: 'Programs01', thumbnail: null },
  ],
  teachers: [
    { id: 'teachers-01', name: 'Teachers 01', component: 'Teachers01', thumbnail: null },
  ],
  facilities: [
    { id: 'facilities-01', name: 'Facilities 01', component: 'Facilities01', thumbnail: null },
  ],
  achievements: [
    { id: 'achievements-01', name: 'Achievements 01', component: 'Achievements01', thumbnail: null },
  ],
  registration: [
    { id: 'registration-01', name: 'Registration 01', component: 'Registration01', thumbnail: null },
  ],
  products: [
    { id: 'products-01', name: 'Aurora — Centered Gradient Glow', component: 'Products01', thumbnail: null },
    { id: 'products-02', name: 'Noir — Full Dark Cinematic', component: 'Products02', thumbnail: null },
    { id: 'products-03', name: 'Transgo — Logistics Split', component: 'Products03', thumbnail: null },
    { id: 'products-04', name: 'Papercut — Brutalist Statement', component: 'Products04', thumbnail: null },
    { id: 'products-05', name: 'Serenity — Minimal Zen', component: 'Products05', thumbnail: null },
    { id: 'products-06', name: 'Nebula — Glass Space Stats', component: 'Products06', thumbnail: null },
    { id: 'products-07', name: 'Terminal — Developer Command', component: 'Products07', thumbnail: null },
    { id: 'products-08', name: 'Sakura — Centered Floral', component: 'Products08', thumbnail: null },
    { id: 'products-09', name: 'Goldleaf — Heritage Gold', component: 'Products09', thumbnail: null },
    { id: 'products-10', name: 'Pulse — Search-First Marketplace', component: 'Products10', thumbnail: null },
    { id: 'products-11', name: 'Iris — Gradient Mesh Playground', component: 'Products11', thumbnail: null },
    { id: 'products-12', name: 'Obsidian — Dark Split Enterprise', component: 'Products12', thumbnail: null },
    { id: 'products-13', name: 'Kioso — Playful Food', component: 'Products13', thumbnail: null },
    { id: 'products-14', name: 'Maison — Corporate Trust', component: 'Products14', thumbnail: null },
    { id: 'products-15', name: 'Monocle — Editorial Magazine', component: 'Products15', thumbnail: null },
    { id: 'products-16', name: 'Emerald — Eco Shop', component: 'Products16', thumbnail: null },
    { id: 'products-17', name: 'Veloce — Sport Full-Bleed', component: 'Products17', thumbnail: null },
    { id: 'products-18', name: 'Solstice — App Download', component: 'Products18', thumbnail: null },
    { id: 'products-19', name: 'Lumière — Agency Portfolio', component: 'Products19', thumbnail: null },
    { id: 'products-20', name: 'Aether — Ultra Premium Finale', component: 'Products20', thumbnail: null },
  ],
  certifications: [
    { id: 'certifications-01', name: 'Certifications 01', component: 'Certifications01', thumbnail: null },
  ],
  vision: [
    { id: 'vision-01', name: 'Aurora — Centered Gradient Glow', component: 'Vision01', thumbnail: null },
    { id: 'vision-02', name: 'Noir — Full Dark Cinematic', component: 'Vision02', thumbnail: null },
    { id: 'vision-03', name: 'Transgo — Logistics Split', component: 'Vision03', thumbnail: null },
    { id: 'vision-04', name: 'Papercut — Brutalist Statement', component: 'Vision04', thumbnail: null },
    { id: 'vision-05', name: 'Serenity — Minimal Zen', component: 'Vision05', thumbnail: null },
    { id: 'vision-06', name: 'Nebula — Glass Space Stats', component: 'Vision06', thumbnail: null },
    { id: 'vision-07', name: 'Terminal — Developer Command', component: 'Vision07', thumbnail: null },
    { id: 'vision-08', name: 'Sakura — Centered Floral', component: 'Vision08', thumbnail: null },
    { id: 'vision-09', name: 'Goldleaf — Heritage Gold', component: 'Vision09', thumbnail: null },
    { id: 'vision-10', name: 'Pulse — Search-First Marketplace', component: 'Vision10', thumbnail: null },
    { id: 'vision-11', name: 'Iris — Gradient Mesh Playground', component: 'Vision11', thumbnail: null },
    { id: 'vision-12', name: 'Obsidian — Dark Split Enterprise', component: 'Vision12', thumbnail: null },
    { id: 'vision-13', name: 'Kioso — Playful Food Hero', component: 'Vision13', thumbnail: null },
    { id: 'vision-14', name: 'Maison — Corporate Trust', component: 'Vision14', thumbnail: null },
    { id: 'vision-15', name: 'Monocle — Editorial Magazine', component: 'Vision15', thumbnail: null },
    { id: 'vision-16', name: 'Emerald — Eco Shop Hero', component: 'Vision16', thumbnail: null },
    { id: 'vision-17', name: 'Veloce — Sport Full-Bleed', component: 'Vision17', thumbnail: null },
    { id: 'vision-18', name: 'Solstice — App Download', component: 'Vision18', thumbnail: null },
    { id: 'vision-19', name: 'Lumière — Agency Portfolio', component: 'Vision19', thumbnail: null },
    { id: 'vision-20', name: 'Aether — Ultra Premium Finale', component: 'Vision20', thumbnail: null },
  ],
  mission: [
    { id: 'mission-01', name: 'Aurora — Centered Gradient Glow', component: 'Mission01', thumbnail: null },
    { id: 'mission-02', name: 'Noir — Full Dark Cinematic', component: 'Mission02', thumbnail: null },
    { id: 'mission-03', name: 'Transgo — Logistics Split', component: 'Mission03', thumbnail: null },
    { id: 'mission-04', name: 'Papercut — Brutalist Statement', component: 'Mission04', thumbnail: null },
    { id: 'mission-05', name: 'Serenity — Minimal Zen', component: 'Mission05', thumbnail: null },
    { id: 'mission-06', name: 'Nebula — Glass Space Stats', component: 'Mission06', thumbnail: null },
    { id: 'mission-07', name: 'Terminal — Developer Command', component: 'Mission07', thumbnail: null },
    { id: 'mission-08', name: 'Sakura — Centered Floral', component: 'Mission08', thumbnail: null },
    { id: 'mission-09', name: 'Goldleaf — Heritage Gold', component: 'Mission09', thumbnail: null },
    { id: 'mission-10', name: 'Pulse — Search-First Marketplace', component: 'Mission10', thumbnail: null },
    { id: 'mission-11', name: 'Iris — Gradient Mesh Playground', component: 'Mission11', thumbnail: null },
    { id: 'mission-12', name: 'Obsidian — Dark Split Enterprise', component: 'Mission12', thumbnail: null },
    { id: 'mission-13', name: 'Kioso — Playful Food Mission', component: 'Mission13', thumbnail: null },
    { id: 'mission-14', name: 'Maison — Corporate Trust', component: 'Mission14', thumbnail: null },
    { id: 'mission-15', name: 'Monocle — Editorial Magazine', component: 'Mission15', thumbnail: null },
    { id: 'mission-16', name: 'Emerald — Eco Shop Mission', component: 'Mission16', thumbnail: null },
    { id: 'mission-17', name: 'Veloce — Sport Full-Bleed', component: 'Mission17', thumbnail: null },
    { id: 'mission-18', name: 'Solstice — App Download', component: 'Mission18', thumbnail: null },
    { id: 'mission-19', name: 'Lumière — Agency Portfolio', component: 'Mission19', thumbnail: null },
    { id: 'mission-20', name: 'Aether — Ultra Premium Finale', component: 'Mission20', thumbnail: null },
  ],
  timeline: [
    { id: 'timeline-01', name: 'Aurora - Centered Milestone Cards', component: 'Timeline01', thumbnail: null },
    { id: 'timeline-02', name: 'Noir - Dark Cinematic Vertical Stepper', component: 'Timeline02', thumbnail: null },
    { id: 'timeline-03', name: 'Veloce - Dark Cinematic Speed Stages', component: 'Timeline03', thumbnail: null },
    { id: 'timeline-04', name: 'Papercut - Neo-Brutalist Milestone Path', component: 'Timeline04', thumbnail: null },
    { id: 'timeline-05', name: 'Serenity - Minimal Zen Milestone Line', component: 'Timeline05', thumbnail: null },
    { id: 'timeline-06', name: 'Nebula - Dark Glass Space Milestones', component: 'Timeline06', thumbnail: null },
    { id: 'timeline-07', name: 'Terminal - Developer Git Commit History', component: 'Timeline07', thumbnail: null },
    { id: 'timeline-08', name: 'Sakura - Warm Gradient Bento Milestones', component: 'Timeline08', thumbnail: null },
    { id: 'timeline-09', name: 'Summit - Navy Corporate Horizon', component: 'Timeline09', thumbnail: null },
    { id: 'timeline-10', name: 'Pulse - Interactive Year Filter Tabs', component: 'Timeline10', thumbnail: null },
    { id: 'timeline-11', name: 'Verdant - Eco Green Sustainability Journey', component: 'Timeline11', thumbnail: null },
    { id: 'timeline-12', name: 'Solstice - Sunset Warm Horizon Track', component: 'Timeline12', thumbnail: null },
    { id: 'timeline-13', name: 'Monocle - Editorial Chronology Spec', component: 'Timeline13', thumbnail: null },
    { id: 'timeline-14', name: 'Zephyr - Glassmorphism AI Evolution', component: 'Timeline14', thumbnail: null },
    { id: 'timeline-15', name: 'Meridian - Vertical Heritage Spine', component: 'Timeline15', thumbnail: null },
    { id: 'timeline-16', name: 'Lumiere - Luxury Agency Roadmap', component: 'Timeline16', thumbnail: null },
    { id: 'timeline-17', name: 'Transgo - Industrial Logistics Milestones', component: 'Timeline17', thumbnail: null },
    { id: 'timeline-18', name: 'Solaris - App Product Launch Roadmap', component: 'Timeline18', thumbnail: null },
    { id: 'timeline-19', name: 'Orion - Split Strategy & Execution', component: 'Timeline19', thumbnail: null },
    { id: 'timeline-20', name: 'Aether - Ultra Premium Visionary Finale', component: 'Timeline20', thumbnail: null },
  ],
  team: [
    { id: 'team-01', name: 'Aurora — Centered Gradient Glow', component: 'Team01', thumbnail: null },
    { id: 'team-02', name: 'Noir — Full Dark Cinematic', component: 'Team02', thumbnail: null },
    { id: 'team-03', name: 'Transgo — Logistics Split', component: 'Team03', thumbnail: null },
    { id: 'team-04', name: 'Papercut — Brutalist Statement', component: 'Team04', thumbnail: null },
    { id: 'team-05', name: 'Serenity — Minimal Zen', component: 'Team05', thumbnail: null },
    { id: 'team-06', name: 'Nebula — Glass Space Stats', component: 'Team06', thumbnail: null },
    { id: 'team-07', name: 'Terminal — Developer Command', component: 'Team07', thumbnail: null },
    { id: 'team-08', name: 'Sakura — Centered Floral', component: 'Team08', thumbnail: null },
    { id: 'team-09', name: 'Goldleaf — Heritage Gold', component: 'Team09', thumbnail: null },
    { id: 'team-10', name: 'Pulse — Search-First Marketplace', component: 'Team10', thumbnail: null },
    { id: 'team-11', name: 'Iris — Gradient Mesh Playground', component: 'Team11', thumbnail: null },
    { id: 'team-12', name: 'Obsidian — Dark Split Enterprise', component: 'Team12', thumbnail: null },
    { id: 'team-13', name: 'Kioso — Playful Food', component: 'Team13', thumbnail: null },
    { id: 'team-14', name: 'Maison — Corporate Trust', component: 'Team14', thumbnail: null },
    { id: 'team-15', name: 'Monocle — Editorial Magazine', component: 'Team15', thumbnail: null },
    { id: 'team-16', name: 'Emerald — Eco Shop', component: 'Team16', thumbnail: null },
    { id: 'team-17', name: 'Veloce — Sport Full-Bleed', component: 'Team17', thumbnail: null },
    { id: 'team-18', name: 'Solstice — App Download', component: 'Team18', thumbnail: null },
    { id: 'team-19', name: 'Lumière — Agency Portfolio', component: 'Team19', thumbnail: null },
    { id: 'team-20', name: 'Aether — Ultra Premium Finale', component: 'Team20', thumbnail: null },
  ],
  faq: [
    { id: 'faq-01', name: 'Aurora — Centered Gradient Glow', component: 'Faq01', thumbnail: null },
    { id: 'faq-02', name: 'Noir — Full Dark Cinematic', component: 'Faq02', thumbnail: null },
    { id: 'faq-03', name: 'Transgo — Logistics Split', component: 'Faq03', thumbnail: null },
    { id: 'faq-04', name: 'Papercut — Brutalist Statement', component: 'Faq04', thumbnail: null },
    { id: 'faq-05', name: 'Serenity — Minimal Zen', component: 'Faq05', thumbnail: null },
    { id: 'faq-06', name: 'Nebula — Glass Space Stats', component: 'Faq06', thumbnail: null },
    { id: 'faq-07', name: 'Terminal — Developer Command', component: 'Faq07', thumbnail: null },
    { id: 'faq-08', name: 'Sakura — Centered Floral', component: 'Faq08', thumbnail: null },
    { id: 'faq-09', name: 'Goldleaf — Heritage Gold', component: 'Faq09', thumbnail: null },
    { id: 'faq-10', name: 'Pulse — Search-First Marketplace', component: 'Faq10', thumbnail: null },
    { id: 'faq-11', name: 'Iris — Gradient Mesh Playground', component: 'Faq11', thumbnail: null },
    { id: 'faq-12', name: 'Obsidian — Dark Split Enterprise', component: 'Faq12', thumbnail: null },
    { id: 'faq-13', name: 'Kioso — Playful Food', component: 'Faq13', thumbnail: null },
    { id: 'faq-14', name: 'Maison — Corporate Trust', component: 'Faq14', thumbnail: null },
    { id: 'faq-15', name: 'Monocle — Editorial Magazine', component: 'Faq15', thumbnail: null },
    { id: 'faq-16', name: 'Emerald — Eco Shop', component: 'Faq16', thumbnail: null },
    { id: 'faq-17', name: 'Veloce — Sport Full-Bleed', component: 'Faq17', thumbnail: null },
    { id: 'faq-18', name: 'Solstice — App Download', component: 'Faq18', thumbnail: null },
    { id: 'faq-19', name: 'Lumière — Agency Portfolio', component: 'Faq19', thumbnail: null },
    { id: 'faq-20', name: 'Aether — Ultra Premium Finale', component: 'Faq20', thumbnail: null },
  ],
  pricing: [
    { id: 'pricing-01', name: 'Aurora — Centered Gradient Glow', component: 'Pricing01', thumbnail: null },
    { id: 'pricing-02', name: 'Noir — Full Dark Cinematic', component: 'Pricing02', thumbnail: null },
    { id: 'pricing-03', name: 'Transgo — Logistics Split', component: 'Pricing03', thumbnail: null },
    { id: 'pricing-04', name: 'Papercut — Brutalist Statement', component: 'Pricing04', thumbnail: null },
    { id: 'pricing-05', name: 'Serenity — Minimal Zen', component: 'Pricing05', thumbnail: null },
    { id: 'pricing-06', name: 'Nebula — Glass Space Stats', component: 'Pricing06', thumbnail: null },
    { id: 'pricing-07', name: 'Terminal — Developer Command', component: 'Pricing07', thumbnail: null },
    { id: 'pricing-08', name: 'Sakura — Centered Floral', component: 'Pricing08', thumbnail: null },
    { id: 'pricing-09', name: 'Goldleaf — Heritage Gold', component: 'Pricing09', thumbnail: null },
    { id: 'pricing-10', name: 'Pulse — Search-First Marketplace', component: 'Pricing10', thumbnail: null },
    { id: 'pricing-11', name: 'Iris — Gradient Mesh Playground', component: 'Pricing11', thumbnail: null },
    { id: 'pricing-12', name: 'Obsidian — Dark Split Enterprise', component: 'Pricing12', thumbnail: null },
    { id: 'pricing-13', name: 'Kioso — Playful Food', component: 'Pricing13', thumbnail: null },
    { id: 'pricing-14', name: 'Maison — Corporate Trust', component: 'Pricing14', thumbnail: null },
    { id: 'pricing-15', name: 'Monocle — Editorial Magazine', component: 'Pricing15', thumbnail: null },
    { id: 'pricing-16', name: 'Emerald — Eco Shop', component: 'Pricing16', thumbnail: null },
    { id: 'pricing-17', name: 'Veloce — Sport Full-Bleed', component: 'Pricing17', thumbnail: null },
    { id: 'pricing-18', name: 'Solstice — App Download', component: 'Pricing18', thumbnail: null },
    { id: 'pricing-19', name: 'Lumière — Agency Portfolio', component: 'Pricing19', thumbnail: null },
    { id: 'pricing-20', name: 'Aether — Ultra Premium Finale', component: 'Pricing20', thumbnail: null },
  ],
  map: [
    { id: 'map-01', name: 'Aurora — Centered Gradient Glow', component: 'Map01', thumbnail: null },
    { id: 'map-02', name: 'Noir — Full Dark Cinematic', component: 'Map02', thumbnail: null },
    { id: 'map-03', name: 'Transgo — Logistics Split', component: 'Map03', thumbnail: null },
    { id: 'map-04', name: 'Papercut — Brutalist Statement', component: 'Map04', thumbnail: null },
    { id: 'map-05', name: 'Serenity — Minimal Zen', component: 'Map05', thumbnail: null },
    { id: 'map-06', name: 'Nebula — Glass Space Stats', component: 'Map06', thumbnail: null },
    { id: 'map-07', name: 'Terminal — Developer Command', component: 'Map07', thumbnail: null },
    { id: 'map-08', name: 'Sakura — Centered Floral', component: 'Map08', thumbnail: null },
    { id: 'map-09', name: 'Goldleaf — Heritage Gold', component: 'Map09', thumbnail: null },
    { id: 'map-10', name: 'Pulse — Search-First Marketplace', component: 'Map10', thumbnail: null },
    { id: 'map-11', name: 'Iris — Gradient Mesh Playground', component: 'Map11', thumbnail: null },
    { id: 'map-12', name: 'Obsidian — Dark Split Enterprise', component: 'Map12', thumbnail: null },
    { id: 'map-13', name: 'Kioso — Playful Food', component: 'Map13', thumbnail: null },
    { id: 'map-14', name: 'Maison — Corporate Trust', component: 'Map14', thumbnail: null },
    { id: 'map-15', name: 'Monocle — Editorial Magazine', component: 'Map15', thumbnail: null },
    { id: 'map-16', name: 'Emerald — Eco Shop', component: 'Map16', thumbnail: null },
    { id: 'map-17', name: 'Veloce — Sport Full-Bleed', component: 'Map17', thumbnail: null },
    { id: 'map-18', name: 'Solstice — App Download', component: 'Map18', thumbnail: null },
    { id: 'map-19', name: 'Lumière — Agency Portfolio', component: 'Map19', thumbnail: null },
    { id: 'map-20', name: 'Aether — Ultra Premium Finale', component: 'Map20', thumbnail: null },
  ],
};

export const getLayoutsForSection = (sectionType) => {
  return LAYOUT_REGISTRY[sectionType] || [];
};

export const getDefaultLayout = (sectionType) => {
  const layouts = LAYOUT_REGISTRY[sectionType];
  return layouts && layouts.length > 0 ? layouts[0].id : null;
};

export const getLayoutComponent = (sectionType, layoutId) => {
  const layouts = LAYOUT_REGISTRY[sectionType];
  if (!layouts) return null;

  const layout = layouts.find(l => l.id === layoutId);
  return layout ? layout.component : null;
};

