import fs from 'fs';
const M=[
['Category created successfully','Kategori berhasil dibuat'],
['Failed to create category','Gagal membuat kategori'],
['Category updated successfully','Kategori berhasil diperbarui'],
['Failed to update category','Gagal memperbarui kategori'],
['Category deleted successfully','Kategori berhasil dihapus'],
['Failed to delete category','Gagal menghapus kategori'],
['Template created successfully','Template berhasil dibuat'],
['Failed to create template','Gagal membuat template'],
['Template updated successfully','Template berhasil diperbarui'],
['Failed to update template','Gagal memperbarui template'],
['Template deleted successfully','Template berhasil dihapus'],
['Failed to delete template','Gagal menghapus template'],
['Sort order updated','Urutan berhasil diperbarui'],
['Category Taxonomy','Taksonomi Kategori'],
['Industry Categories','Kategori Industri'],
['Add Category','Tambah Kategori'],
['Search by category name or slug...','Cari berdasarkan nama kategori atau slug...'],
['Loading categories...','Memuat kategori...'],
['No categories found matching search.','Tidak ada kategori yang cocok dengan pencarian.'],
['Sort Order','Urutan'],
['Created At','Dibuat Pada'],
['Updated At','Diperbarui Pada'],
['Move Up','Pindah ke Atas'],
['Move Down','Pindah ke Bawah'],
['Manage Templates','Kelola Template'],
['Edit Category','Ubah Kategori'],
['Delete Category','Hapus Kategori'],
['Add New Category','Tambah Kategori Baru'],
['Category Name','Nama Kategori'],
['Template Name','Nama Template'],
['Template description...','Deskripsi template...'],
['Thumbnail URL','URL Thumbnail'],
['Edit Template','Ubah Template'],
['Add New Template','Tambah Template Baru'],
['Total Hosted Sites','Total Situs Dihosting'],
['Draft Sites','Situs Draf'],
['Suspended Sites','Situs Ditangguhkan'],
['Platform Administration','Administrasi Platform'],
['All Published & User Websites','Semua Website Terpublikasi & Pengguna'],
['Unknown User','Pengguna Tidak Diketahui'],
['Total Revenue (Paid)','Total Pendapatan (Terbayar)'],
['Admin Revenue & Transactions','Pendapatan & Transaksi Admin'],
['Real-Time System Intelligence','Kecerdasan Sistem Real-Time'],
['Platform & Server Analytics','Analitik Platform & Server'],
['Refresh Realtime','Muat Ulang Real-Time'],
['PHP Environment','Lingkungan PHP'],
['RAM Memory Load','Beban Memori RAM'],
['Website Trafik Tertinggi','Website Trafik Tertinggi'],
['Top 5','5 Teratas'],
['Please check your credentials and try again.','Periksa kredensial Anda dan coba lagi.'],
['Live Builder Engine','Mesin Builder Langsung'],
['with Microdata.','bersama Microdata.'],
['MICRODATA STUDIO 2.0','MICRODATA STUDIO 2.0'],
['DATASOFT STUDIO','DATASOFT STUDIO'],
];
let c=0;function walk(d,a=[]){for(const e of fs.readdirSync(d,{withFileTypes:true})){const p=d+'/'+e.name;if(p.includes('node_modules')||p.includes('.kilo'))continue;if(e.isDirectory())walk(p,a);else if(/\.(jsx|js)$/.test(p))a.push(p);}return a;}
const files=walk('resources/js');for(const f of files){let s=fs.readFileSync(f,'utf8');const o=s;for(const[a,b]of M){if(s.includes(a))s=s.split(a).join(b);}if(s!==o){fs.writeFileSync(f,s);c++;}}
console.log('D changed='+c);
