import fs from 'fs';
const M=[
['Manage industry categories and website starter taxonomies.','Kelola kategori industri dan taksonomi starter website.'],
['>Name<','>Nama<'],
['>Slug<','>Slug<'],
['>Actions<','>Aksi<'],
['>Status<','>Status<'],
['Template Manager','Pengelola Template'],
['System Templates','Template Sistem'],
['Create, upload, and update default corporate website templates for Microdata users.','Buat, unggah, dan perbarui template website korporat bawaan untuk pengguna Microdata.'],
['New Template','Template Baru'],
['Search templates by name, code, or description...','Cari template berdasarkan nama, kode, atau deskripsi...'],
['All Categories','Semua Kategori'],
['>Active<','>Aktif<'],
['Live Preview in New Tab','Pratinjau Langsung di Tab Baru'],
['Edit Details','Ubah Detail'],
['Publish (Aktifkan)','Publikasikan (Aktifkan)'],
['Set to Draft','Jadikan Draf'],
['Disable (Sembunyikan)','Nonaktifkan (Sembunyikan)'],
['Auto-generated if empty','Otomatis jika kosong'],
['Auto-generated from name','Otomatis dari nama'],
['Description and thumbnail required','Deskripsi dan thumbnail wajib diisi'],
['Failed to update template status','Gagal memperbarui status template'],
['Failed to change template status to draft','Gagal mengubah status template menjadi draf'],
['Failed to fetch admin analytics:','Gagal memuat analitik admin:'],
['>hits<','>kunjungan<'],
['>views<','>tayangan<'],
['>IP<','>IP<'],
['Top 5','5 Teratas'],
['Real-Time System Intelligence','Kecerdasan Sistem Real-Time'],
['Please check your credentials and try again.','Periksa kredensial Anda dan coba lagi.'],
['Live Builder Engine','Mesin Builder Langsung'],
['with Microdata.','bersama Microdata.'],
['Total Hosted Sites','Total Situs Dihosting'],
['Draft Sites','Situs Draf'],
['Suspended Sites','Situs Ditangguhkan'],
['All Published & User Websites','Semua Website Terpublikasi & Pengguna'],
['Unknown User','Pengguna Tidak Diketahui'],
['Unpublish','Batal Publikasi'],
['>Publish<','>Publikasikan<'],
['Professional Templates','Template Profesional'],
['Curated templates for Corporate, Logistics, Manufacturing, Education, Cooperatives, and Startups.','Template pilihan untuk Korporat, Logistik, Manufaktur, Pendidikan, Koperasi, dan Startup.'],
['One Click Publish','Publikasi Satu Klik'],
['Responsive Design','Desain Responsif'],
['Every template is automatically optimized for Desktop, Tablet, and Mobile screens.','Setiap template otomatis dioptimalkan untuk layar Desktop, Tablet, dan Ponsel.'],
['Theme Customizer','Penyesuai Tema'],
['Change colors, fonts, spacing, and layouts instantly with real-time live preview updates.','Ubah warna, font, jarak, dan tata letak seketika dengan pratinjau langsung.'],
['Media Manager','Pengelola Media'],
['Upload and manage images, videos, logos, and documents in an organized media library.','Unggah dan kelola gambar, video, logo, dan dokumen dalam galeri media yang rapi.'],
['Contact Sales','Hubungi Penjualan'],
['Build Professional Websites','Bangun Website Profesional'],
['With One-Click Hosting','Dengan Hosting Satu Klik'],
['Create, customize, and publish stunning websites using a visual drag-and-drop builder without writing a single line of c','Buat, sesuaikan, dan publikasikan website memukau memakai builder seret & letakkan tanpa menulis satu baris pun k'],
['Everything Needed to Launch Websites Faster','Semua yang Dibutuhkan untuk Meluncurkan Website Lebih Cepat'],
['How It Works','Cara Kerja'],
['The template library is incredible. Professional designs that perfectly match our educational institution brand.','Pustaka templatenya luar biasa. Desain profesional yang sangat cocok dengan brand institusi pendidikan kami.'],
['From zero to published in under 2 hours. The drag and drop builder is as intuitive as Canva. Absolutely love it.','Dari nol hingga publikasi kurang dari 2 jam. Builder seret & letakkannya seintuitif Canva. Sangat suka.'],
['Drag left/right or tap a tab to rotate 3D pricing wheel.','Geser ke kiri/kanan atau ketuk tab untuk memutar roda harga 3D.'],
['Color Palette','Palet Warna'],
['Font Family','Jenis Font'],
['Container Gap','Jarak Kontainer'],
['Real-time Analytics','Analitik Real-time'],
['Component Based','Berbasis Komponen'],
['Failed to load Midtrans Snap JS','Gagal memuat Midtrans Snap JS'],
['Billing & Subscriptions','Tagihan & Langganan'],
['Nothing here yet','Belum ada data'],
['Global Administration','Administrasi Global'],
['System Settings','Pengaturan Sistem'],
['Live Preview','Pratinjau Langsung'],
['Brand Logo','Logo Brand'],
['Appears in sidebar, navbar, and footer.','Tampil di bilah sisi, bilah atas, dan footer.'],
['Shown inside the colored logo box if no image logo.','Ditampilkan di dalam kotak logo berwarna jika tanpa logo gambar.'],
['Text shown below brand name in sidebar header.','Teks di bawah nama brand pada kepala bilah sisi.'],
['Used for logo box, active nav items, and buttons.','Dipakai untuk kotak logo, menu aktif, dan tombol.'],
['Logo Preview','Pratinjau Logo'],
['Custom logo uploaded','Logo kustom terunggah'],
['This replaces the text badge box in navbar and sidebar.','Ini menggantikan kotak badge teks di navbar dan bilah sisi.'],
['Remove logo','Hapus logo'],
['Click to upload logo image','Klik untuk mengunggah gambar logo'],
['Apply Brand Changes','Terapkan Perubahan Brand'],
['Saving...','Menyimpan...'],
];
function walk(d,a=[]){for(const e of fs.readdirSync(d,{withFileTypes:true})){const p=d+'/'+e.name;if(p.includes('node_modules')||p.includes('.kilo'))continue;if(e.isDirectory())walk(p,a);else if(/\.(jsx|js)$/.test(p))a.push(p);}return a;}
const files=walk('resources/js');let c=0;for(const f of files){let s=fs.readFileSync(f,'utf8');const o=s;for(const[a,b]of M){if(s.includes(a))s=s.split(a).join(b);}if(s!==o){fs.writeFileSync(f,s);c++;}}
console.log('E changed='+c);
