import { renderLayoutComponents } from '../../../engine/layoutRenderer.jsx';

export default function Faq08({ components = [], sectionId = null }) {
  const defaultComponents = [
    { id: 'faq8-badge', type: 'badge', props: { content: 'FAQ', background: '#fce7f3', color: '#be185d' } },
    { id: 'faq8-heading', type: 'heading', props: { content: 'Pertanyaan yang Sering Diajukan', level: 'h2', fontSize: '40px', fontWeight: '800', color: '#831843', align: 'center', margin: '0 0 12px 0' } },
    { id: 'faq8-text', type: 'text', props: { content: 'Jawaban atas pertanyaan paling umum dari pelanggan kami.', fontSize: '15px', color: '#9d7b8c', align: 'center', margin: '0 0 20px 0' } },
    { id: 'faq8-cta', type: 'button', props: { label: 'Hubungi Kami', href: '#kontak', variant: 'primary', size: 'medium', radius: 'full', background: '#db2777', color: '#ffffff' } },
    { id: 'faq8-item-1', type: 'card', props: { variant: 'faq', background: '#fff1f2', borderRadius: '16px', shadow: 'none', borderWidth: '1px', borderColor: '#fff1f2', hoverEffect: 'none', padding: '24px' }, childrenComponents: [ { id: 'faq8-i1-q', type: 'heading', props: { content: 'Layanan apa yang tersedia untuk bisnis kami?', level: 'h4', fontSize: '16px', fontWeight: '700', color: '#831843', margin: '0 0 10px 0' } }, { id: 'faq8-i1-a', type: 'text', props: { content: 'Konsultasi, implementasi, pelatihan, dan dukungan purna jual.', fontSize: '14px', color: '#9d7b8c', margin: '0' } }, { id: 'faq8-i1-btn', type: 'button', props: { label: 'Pelajari', href: '#bantuan', variant: 'ghost', size: 'small', background: 'transparent', color: '#9d7b8c' } } ] },
    { id: 'faq8-item-2', type: 'card', props: { variant: 'faq', background: '#fff1f2', borderRadius: '16px', shadow: 'none', borderWidth: '1px', borderColor: '#fff1f2', hoverEffect: 'none', padding: '24px' }, childrenComponents: [ { id: 'faq8-i2-q', type: 'heading', props: { content: 'Berapa lama proses implementasi?', level: 'h4', fontSize: '16px', fontWeight: '700', color: '#831843', margin: '0 0 10px 0' } }, { id: 'faq8-i2-a', type: 'text', props: { content: 'Implementasi 2-8 minggu tergantung skala kebutuhan.', fontSize: '14px', color: '#9d7b8c', margin: '0' } }, { id: 'faq8-i2-btn', type: 'button', props: { label: 'Pelajari', href: '#bantuan', variant: 'ghost', size: 'small', background: 'transparent', color: '#9d7b8c' } } ] },
    { id: 'faq8-item-3', type: 'card', props: { variant: 'faq', background: '#fff1f2', borderRadius: '16px', shadow: 'none', borderWidth: '1px', borderColor: '#fff1f2', hoverEffect: 'none', padding: '24px' }, childrenComponents: [ { id: 'faq8-i3-q', type: 'heading', props: { content: 'Apakah ada paket harga fleksibel?', level: 'h4', fontSize: '16px', fontWeight: '700', color: '#831843', margin: '0 0 10px 0' } }, { id: 'faq8-i3-a', type: 'text', props: { content: 'Ya, tersedia paket UMKM, menengah, hingga enterprise.', fontSize: '14px', color: '#9d7b8c', margin: '0' } }, { id: 'faq8-i3-btn', type: 'button', props: { label: 'Pelajari', href: '#bantuan', variant: 'ghost', size: 'small', background: 'transparent', color: '#9d7b8c' } } ] },
    { id: 'faq8-item-4', type: 'card', props: { variant: 'faq', background: '#fff1f2', borderRadius: '16px', shadow: 'none', borderWidth: '1px', borderColor: '#fff1f2', hoverEffect: 'none', padding: '24px' }, childrenComponents: [ { id: 'faq8-i4-q', type: 'heading', props: { content: 'Bagaimana dukungan teknis bekerja?', level: 'h4', fontSize: '16px', fontWeight: '700', color: '#831843', margin: '0 0 10px 0' } }, { id: 'faq8-i4-a', type: 'text', props: { content: 'Dukungan 24/7 via live chat, email, dan telepon.', fontSize: '14px', color: '#9d7b8c', margin: '0' } }, { id: 'faq8-i4-btn', type: 'button', props: { label: 'Pelajari', href: '#bantuan', variant: 'ghost', size: 'small', background: 'transparent', color: '#9d7b8c' } } ] },
  ];
  const layoutComponents = components.length > 0 ? components : defaultComponents;
  const header = layoutComponents.filter((c) => c.type !== 'card');
  const cards = layoutComponents.filter((c) => c.type === 'card');
  return ( <section className="py-24 px-6 bg-gradient-to-b from-pink-50 to-white"> <div className="flex items-center justify-center gap-2 my-1 select-none pointer-events-none"><div className="w-12 h-px bg-pink-300" /><span className="text-pink-400">✦</span><div className="w-12 h-px bg-pink-300" /></div> <div className="relative max-w-3xl mx-auto flex flex-col items-center text-center"> {renderLayoutComponents(header.filter((c) => c.type === 'badge'), sectionId)} <div className="mt-4 w-full">{renderLayoutComponents(header.filter((c) => c.type === 'heading'), sectionId)}</div> <div className="max-w-2xl">{renderLayoutComponents(header.filter((c) => c.type === 'text'), sectionId)}</div> <div className="mt-1">{renderLayoutComponents(header.filter((c) => c.type === 'button'), sectionId)}</div> <div className="w-full mt-8 space-y-4 text-left"> {renderLayoutComponents(cards, sectionId)} </div> </div> </section> );
}
