import { renderLayoutComponents } from '../../../engine/layoutRenderer.jsx';

export default function Faq06({ components = [], sectionId = null }) {
  const defaultComponents = [
    { id: 'faq6-badge', type: 'badge', props: { content: 'FAQ', background: '#1e1b4b', color: '#a5b4fc' } },
    { id: 'faq6-heading', type: 'heading', props: { content: 'Pertanyaan yang Sering Diajukan', level: 'h2', fontSize: '40px', fontWeight: '800', color: '#ffffff', align: 'center', margin: '0 0 12px 0' } },
    { id: 'faq6-text', type: 'text', props: { content: 'Jawaban atas pertanyaan paling umum dari pelanggan kami.', fontSize: '15px', color: '#a5b4fc', align: 'center', margin: '0 0 20px 0' } },
    { id: 'faq6-cta', type: 'button', props: { label: 'Hubungi Kami', href: '#kontak', variant: 'primary', size: 'medium', radius: 'full', background: '#8b5cf6', color: '#ffffff' } },
    { id: 'faq6-item-1', type: 'card', props: { variant: 'faq', background: 'rgba(255,255,255,0.06)', borderRadius: '16px', shadow: 'none', borderWidth: '1px', borderColor: 'rgba(165,180,252,0.25)', hoverEffect: 'none', padding: '24px' }, childrenComponents: [ { id: 'faq6-i1-q', type: 'heading', props: { content: 'Layanan apa yang tersedia untuk bisnis kami?', level: 'h4', fontSize: '16px', fontWeight: '700', color: '#ffffff', margin: '0 0 10px 0' } }, { id: 'faq6-i1-a', type: 'text', props: { content: 'Konsultasi, implementasi, pelatihan, dan dukungan purna jual.', fontSize: '14px', color: '#a5b4fc', margin: '0' } }, { id: 'faq6-i1-btn', type: 'button', props: { label: 'Pelajari', href: '#bantuan', variant: 'ghost', size: 'small', background: 'transparent', color: '#a5b4fc' } } ] },
    { id: 'faq6-item-2', type: 'card', props: { variant: 'faq', background: 'rgba(255,255,255,0.06)', borderRadius: '16px', shadow: 'none', borderWidth: '1px', borderColor: 'rgba(165,180,252,0.25)', hoverEffect: 'none', padding: '24px' }, childrenComponents: [ { id: 'faq6-i2-q', type: 'heading', props: { content: 'Berapa lama proses implementasi?', level: 'h4', fontSize: '16px', fontWeight: '700', color: '#ffffff', margin: '0 0 10px 0' } }, { id: 'faq6-i2-a', type: 'text', props: { content: 'Implementasi 2-8 minggu tergantung skala kebutuhan.', fontSize: '14px', color: '#a5b4fc', margin: '0' } }, { id: 'faq6-i2-btn', type: 'button', props: { label: 'Pelajari', href: '#bantuan', variant: 'ghost', size: 'small', background: 'transparent', color: '#a5b4fc' } } ] },
    { id: 'faq6-item-3', type: 'card', props: { variant: 'faq', background: 'rgba(255,255,255,0.06)', borderRadius: '16px', shadow: 'none', borderWidth: '1px', borderColor: 'rgba(165,180,252,0.25)', hoverEffect: 'none', padding: '24px' }, childrenComponents: [ { id: 'faq6-i3-q', type: 'heading', props: { content: 'Apakah ada paket harga fleksibel?', level: 'h4', fontSize: '16px', fontWeight: '700', color: '#ffffff', margin: '0 0 10px 0' } }, { id: 'faq6-i3-a', type: 'text', props: { content: 'Ya, tersedia paket UMKM, menengah, hingga enterprise.', fontSize: '14px', color: '#a5b4fc', margin: '0' } }, { id: 'faq6-i3-btn', type: 'button', props: { label: 'Pelajari', href: '#bantuan', variant: 'ghost', size: 'small', background: 'transparent', color: '#a5b4fc' } } ] },
    { id: 'faq6-item-4', type: 'card', props: { variant: 'faq', background: 'rgba(255,255,255,0.06)', borderRadius: '16px', shadow: 'none', borderWidth: '1px', borderColor: 'rgba(165,180,252,0.25)', hoverEffect: 'none', padding: '24px' }, childrenComponents: [ { id: 'faq6-i4-q', type: 'heading', props: { content: 'Bagaimana dukungan teknis bekerja?', level: 'h4', fontSize: '16px', fontWeight: '700', color: '#ffffff', margin: '0 0 10px 0' } }, { id: 'faq6-i4-a', type: 'text', props: { content: 'Dukungan 24/7 via live chat, email, dan telepon.', fontSize: '14px', color: '#a5b4fc', margin: '0' } }, { id: 'faq6-i4-btn', type: 'button', props: { label: 'Pelajari', href: '#bantuan', variant: 'ghost', size: 'small', background: 'transparent', color: '#a5b4fc' } } ] },
  ];
  const layoutComponents = components.length > 0 ? components : defaultComponents;
  const header = layoutComponents.filter((c) => c.type !== 'card');
  const cards = layoutComponents.filter((c) => c.type === 'card');
  return ( <section className="relative py-24 px-6 bg-slate-950 overflow-hidden"> <div className="pointer-events-none absolute -top-24 left-1/4 w-[420px] h-[420px] rounded-full bg-gradient-to-br from-violet-600/30 via-indigo-500/25 to-transparent blur-3xl animate-pulse" /> <div className="relative max-w-3xl mx-auto flex flex-col items-center text-center"> {renderLayoutComponents(header.filter((c) => c.type === 'badge'), sectionId)} <div className="mt-4 w-full">{renderLayoutComponents(header.filter((c) => c.type === 'heading'), sectionId)}</div> <div className="max-w-2xl">{renderLayoutComponents(header.filter((c) => c.type === 'text'), sectionId)}</div> <div className="mt-1">{renderLayoutComponents(header.filter((c) => c.type === 'button'), sectionId)}</div> <div className="w-full mt-8 space-y-4 text-left"> {renderLayoutComponents(cards, sectionId)} </div> </div> </section> );
}
