import { renderLayoutComponents } from '../../../engine/layoutRenderer.jsx';

export default function Faq16({ components = [], sectionId = null }) {
  const defaultComponents = [
    { id: 'faq16-badge', type: 'badge', props: { content: 'FAQ', background: '#dcfce7', color: '#166534' } },
    { id: 'faq16-heading', type: 'heading', props: { content: 'Pertanyaan yang Sering Diajukan', level: 'h2', fontSize: '40px', fontWeight: '800', color: '#064e3b', align: 'center', margin: '0 0 12px 0' } },
    { id: 'faq16-text', type: 'text', props: { content: 'Jawaban atas pertanyaan paling umum dari pelanggan kami.', fontSize: '15px', color: '#4d7c0f', align: 'center', margin: '0 0 20px 0' } },
    { id: 'faq16-cta', type: 'button', props: { label: 'Hubungi Kami', href: '#kontak', variant: 'primary', size: 'medium', radius: 'full', background: '#16a34a', color: '#ffffff' } },
    { id: 'faq16-item-1', type: 'card', props: { variant: 'faq', background: '#f0fdf4', borderRadius: '16px', shadow: 'none', borderWidth: '1px', borderColor: '#bbf7d0', hoverEffect: 'none', padding: '24px' }, childrenComponents: [ { id: 'faq16-i1-q', type: 'heading', props: { content: 'Layanan apa yang tersedia untuk bisnis kami?', level: 'h4', fontSize: '16px', fontWeight: '700', color: '#064e3b', margin: '0 0 10px 0' } }, { id: 'faq16-i1-a', type: 'text', props: { content: 'Konsultasi, implementasi, pelatihan, dan dukungan purna jual.', fontSize: '14px', color: '#166534', margin: '0' } }, { id: 'faq16-i1-btn', type: 'button', props: { label: 'Pelajari', href: '#bantuan', variant: 'ghost', size: 'small', background: 'transparent', color: '#166534' } } ] },
    { id: 'faq16-item-2', type: 'card', props: { variant: 'faq', background: '#f0fdf4', borderRadius: '16px', shadow: 'none', borderWidth: '1px', borderColor: '#bbf7d0', hoverEffect: 'none', padding: '24px' }, childrenComponents: [ { id: 'faq16-i2-q', type: 'heading', props: { content: 'Berapa lama proses implementasi?', level: 'h4', fontSize: '16px', fontWeight: '700', color: '#064e3b', margin: '0 0 10px 0' } }, { id: 'faq16-i2-a', type: 'text', props: { content: 'Implementasi 2-8 minggu tergantung skala kebutuhan.', fontSize: '14px', color: '#166534', margin: '0' } }, { id: 'faq16-i2-btn', type: 'button', props: { label: 'Pelajari', href: '#bantuan', variant: 'ghost', size: 'small', background: 'transparent', color: '#166534' } } ] },
    { id: 'faq16-item-3', type: 'card', props: { variant: 'faq', background: '#f0fdf4', borderRadius: '16px', shadow: 'none', borderWidth: '1px', borderColor: '#bbf7d0', hoverEffect: 'none', padding: '24px' }, childrenComponents: [ { id: 'faq16-i3-q', type: 'heading', props: { content: 'Apakah ada paket harga fleksibel?', level: 'h4', fontSize: '16px', fontWeight: '700', color: '#064e3b', margin: '0 0 10px 0' } }, { id: 'faq16-i3-a', type: 'text', props: { content: 'Ya, tersedia paket UMKM, menengah, hingga enterprise.', fontSize: '14px', color: '#166534', margin: '0' } }, { id: 'faq16-i3-btn', type: 'button', props: { label: 'Pelajari', href: '#bantuan', variant: 'ghost', size: 'small', background: 'transparent', color: '#166534' } } ] },
    { id: 'faq16-item-4', type: 'card', props: { variant: 'faq', background: '#f0fdf4', borderRadius: '16px', shadow: 'none', borderWidth: '1px', borderColor: '#bbf7d0', hoverEffect: 'none', padding: '24px' }, childrenComponents: [ { id: 'faq16-i4-q', type: 'heading', props: { content: 'Bagaimana dukungan teknis bekerja?', level: 'h4', fontSize: '16px', fontWeight: '700', color: '#064e3b', margin: '0 0 10px 0' } }, { id: 'faq16-i4-a', type: 'text', props: { content: 'Dukungan 24/7 via live chat, email, dan telepon.', fontSize: '14px', color: '#166534', margin: '0' } }, { id: 'faq16-i4-btn', type: 'button', props: { label: 'Pelajari', href: '#bantuan', variant: 'ghost', size: 'small', background: 'transparent', color: '#166534' } } ] },
  ];
  const layoutComponents = components.length > 0 ? components : defaultComponents;
  const header = layoutComponents.filter((c) => c.type !== 'card');
  const cards = layoutComponents.filter((c) => c.type === 'card');
  return ( <section className="py-20 px-6 bg-gradient-to-b from-green-50 to-white">  <div className="relative max-w-3xl mx-auto flex flex-col items-center text-center"> {renderLayoutComponents(header.filter((c) => c.type === 'badge'), sectionId)} <div className="mt-4 w-full">{renderLayoutComponents(header.filter((c) => c.type === 'heading'), sectionId)}</div> <div className="max-w-2xl">{renderLayoutComponents(header.filter((c) => c.type === 'text'), sectionId)}</div> <div className="mt-1">{renderLayoutComponents(header.filter((c) => c.type === 'button'), sectionId)}</div> <div className="w-full mt-8 space-y-4 text-left"> {renderLayoutComponents(cards, sectionId)} </div> </div> </section> );
}
