import { renderLayoutComponents } from '../../../engine/layoutRenderer.jsx';
export default function Contact07({ components = [], sectionId = null }) {
  const defaultComponents = [
    { id: 'ct7-badge', type: 'badge', props: { content: 'Kontak', background: '#052e16', color: '#4ade80' } },
    { id: 'ct7-heading', type: 'heading', props: { content: 'Hubungi Kami', level: 'h2', fontSize: '40px', fontWeight: '800', color: '#e2e8f0', align: 'center', margin: '0 0 12px 0' } },
    { id: 'ct7-text', type: 'text', props: { content: 'Tim kami siap membantu Senin-Sabtu 08.00-17.00.', fontSize: '15px', color: '#94a3b8', align: 'center', margin: '0 0 20px 0' } },
    { id: 'ct7-cta', type: 'button', props: { label: 'Kirim Pesan', href: '#pesan', variant: 'primary', size: 'medium', radius: 'full', background: '#22c55e', color: '#052e16' } },
    { id: 'ct7-cta2', type: 'button', props: { label: 'WhatsApp', href: '#wa', variant: 'ghost', size: 'medium', background: 'transparent', color: '#e2e8f0' } },
    { id: 'ct7-card-1', type: 'card', props: { variant: 'default', background: '#0f172a', borderRadius: '16px', shadow: 'sm', borderWidth: '1px', borderColor: '#1e293b', hoverEffect: 'lift', padding: '20px' }, childrenComponents: [ { id: 'ct7-c1-icon', type: 'icon', props: { icon: 'FaMapMarkerAlt', size: '28px', color: '#22c55e', align: 'left' } }, { id: 'ct7-c1-title', type: 'heading', props: { content: 'Address', level: 'h4', fontSize: '15px', fontWeight: '700', color: '#e2e8f0', margin: '8px 0 2px 0' } }, { id: 'ct7-c1-desc', type: 'text', props: { content: 'Jl. Merdeka No. 123, Jakarta', fontSize: '14px', color: '#94a3b8', margin: '0' } } ] },
    { id: 'ct7-card-2', type: 'card', props: { variant: 'default', background: '#0f172a', borderRadius: '16px', shadow: 'sm', borderWidth: '1px', borderColor: '#1e293b', hoverEffect: 'lift', padding: '20px' }, childrenComponents: [ { id: 'ct7-c2-icon', type: 'icon', props: { icon: 'FaPhone', size: '28px', color: '#22c55e', align: 'left' } }, { id: 'ct7-c2-title', type: 'heading', props: { content: 'Phone', level: 'h4', fontSize: '15px', fontWeight: '700', color: '#e2e8f0', margin: '8px 0 2px 0' } }, { id: 'ct7-c2-desc', type: 'text', props: { content: '+62 21 555 0123', fontSize: '14px', color: '#94a3b8', margin: '0' } } ] },
    { id: 'ct7-card-3', type: 'card', props: { variant: 'default', background: '#0f172a', borderRadius: '16px', shadow: 'sm', borderWidth: '1px', borderColor: '#1e293b', hoverEffect: 'lift', padding: '20px' }, childrenComponents: [ { id: 'ct7-c3-icon', type: 'icon', props: { icon: 'FaEnvelope', size: '28px', color: '#22c55e', align: 'left' } }, { id: 'ct7-c3-title', type: 'heading', props: { content: 'Email', level: 'h4', fontSize: '15px', fontWeight: '700', color: '#e2e8f0', margin: '8px 0 2px 0' } }, { id: 'ct7-c3-desc', type: 'text', props: { content: 'hello@company.com', fontSize: '14px', color: '#94a3b8', margin: '0' } } ] },
  ];
  const layoutComponents = components.length > 0 ? components : defaultComponents;
  const header = layoutComponents.filter((c) => c.type !== 'card');
  const cards = layoutComponents.filter((c) => c.type === 'card');
  return ( <section className="py-20 px-6 bg-[#020617] font-mono"> <div className="flex items-center gap-1.5 mb-6 select-none pointer-events-none"><span className="w-3 h-3 rounded-full bg-red-500" /><span className="w-3 h-3 rounded-full bg-yellow-500" /><span className="w-3 h-3 rounded-full bg-green-500" /></div> <div className="relative max-w-6xl mx-auto flex flex-col items-center text-center"> {renderLayoutComponents(header.filter((c) => c.type === 'badge'), sectionId)} <div className="mt-4 w-full">{renderLayoutComponents(header.filter((c) => c.type === 'heading'), sectionId)}</div> <div className="max-w-2xl">{renderLayoutComponents(header.filter((c) => c.type === 'text'), sectionId)}</div> <div className="flex flex-wrap justify-center gap-3 mt-1">{renderLayoutComponents(header.filter((c) => c.type === 'button'), sectionId)}</div> <div className="grid grid-cols-1 md:grid-cols-3 gap-5 w-full mt-10 text-left"> {renderLayoutComponents(cards, sectionId)} </div> <div className="w-full max-w-2xl mt-8 rounded-2xl border p-4 flex gap-3 select-none pointer-events-none" style={{ borderColor: '#1e293b', background: '#0f172a' }}> <input placeholder="Nama" /> <input placeholder="Email" /> </div> </div> </section> );
}
