import { renderLayoutComponents } from '../../../engine/layoutRenderer.jsx';
export default function Contact13({ components = [], sectionId = null }) {
  const defaultComponents = [
    { id: 'ct13-badge', type: 'badge', props: { content: 'Kontak', background: '#fce7f3', color: '#ec4899' } },
    { id: 'ct13-heading', type: 'heading', props: { content: 'Hubungi Kami', level: 'h2', fontSize: '40px', fontWeight: '800', color: '#0f172a', align: 'center', margin: '0 0 12px 0' } },
    { id: 'ct13-text', type: 'text', props: { content: 'Tim kami siap membantu Senin-Sabtu 08.00-17.00.', fontSize: '15px', color: '#64748b', align: 'center', margin: '0 0 20px 0' } },
    { id: 'ct13-cta', type: 'button', props: { label: 'Kirim Pesan', href: '#pesan', variant: 'primary', size: 'medium', radius: 'full', background: '#ec4899', color: '#ffffff' } },
    { id: 'ct13-cta2', type: 'button', props: { label: 'WhatsApp', href: '#wa', variant: 'ghost', size: 'medium', background: 'transparent', color: '#0f172a' } },
    { id: 'ct13-card-1', type: 'card', props: { variant: 'default', background: '#fff1f2', borderRadius: '16px', shadow: 'sm', borderWidth: '1px', borderColor: '#fff1f2', hoverEffect: 'lift', padding: '20px' }, childrenComponents: [ { id: 'ct13-c1-icon', type: 'icon', props: { icon: 'FaMapMarkerAlt', size: '28px', color: '#ec4899', align: 'left' } }, { id: 'ct13-c1-title', type: 'heading', props: { content: 'Address', level: 'h4', fontSize: '15px', fontWeight: '700', color: '#0f172a', margin: '8px 0 2px 0' } }, { id: 'ct13-c1-desc', type: 'text', props: { content: 'Jl. Merdeka No. 123, Jakarta', fontSize: '14px', color: '#64748b', margin: '0' } } ] },
    { id: 'ct13-card-2', type: 'card', props: { variant: 'default', background: '#fff1f2', borderRadius: '16px', shadow: 'sm', borderWidth: '1px', borderColor: '#fff1f2', hoverEffect: 'lift', padding: '20px' }, childrenComponents: [ { id: 'ct13-c2-icon', type: 'icon', props: { icon: 'FaPhone', size: '28px', color: '#ec4899', align: 'left' } }, { id: 'ct13-c2-title', type: 'heading', props: { content: 'Phone', level: 'h4', fontSize: '15px', fontWeight: '700', color: '#0f172a', margin: '8px 0 2px 0' } }, { id: 'ct13-c2-desc', type: 'text', props: { content: '+62 21 555 0123', fontSize: '14px', color: '#64748b', margin: '0' } } ] },
    { id: 'ct13-card-3', type: 'card', props: { variant: 'default', background: '#fff1f2', borderRadius: '16px', shadow: 'sm', borderWidth: '1px', borderColor: '#fff1f2', hoverEffect: 'lift', padding: '20px' }, childrenComponents: [ { id: 'ct13-c3-icon', type: 'icon', props: { icon: 'FaEnvelope', size: '28px', color: '#ec4899', align: 'left' } }, { id: 'ct13-c3-title', type: 'heading', props: { content: 'Email', level: 'h4', fontSize: '15px', fontWeight: '700', color: '#0f172a', margin: '8px 0 2px 0' } }, { id: 'ct13-c3-desc', type: 'text', props: { content: 'hello@company.com', fontSize: '14px', color: '#64748b', margin: '0' } } ] },
  ];
  const layoutComponents = components.length > 0 ? components : defaultComponents;
  const header = layoutComponents.filter((c) => c.type !== 'card');
  const cards = layoutComponents.filter((c) => c.type === 'card');
  return ( <section className="py-20 px-6 bg-gradient-to-b from-rose-50 to-amber-50">  <div className="relative max-w-6xl mx-auto flex flex-col items-center text-center"> {renderLayoutComponents(header.filter((c) => c.type === 'badge'), sectionId)} <div className="mt-4 w-full">{renderLayoutComponents(header.filter((c) => c.type === 'heading'), sectionId)}</div> <div className="max-w-2xl">{renderLayoutComponents(header.filter((c) => c.type === 'text'), sectionId)}</div> <div className="flex flex-wrap justify-center gap-3 mt-1">{renderLayoutComponents(header.filter((c) => c.type === 'button'), sectionId)}</div> <div className="grid grid-cols-1 md:grid-cols-3 gap-5 w-full mt-10 text-left"> {renderLayoutComponents(cards, sectionId)} </div> <div className="w-full max-w-2xl mt-8 rounded-2xl border p-4 flex gap-3 select-none pointer-events-none" style={{ borderColor: '#fff1f2', background: '#fff1f2' }}> <input placeholder="Nama" /> <input placeholder="Email" /> </div> </div> </section> );
}
