import { renderLayoutComponents } from '../../../engine/layoutRenderer.jsx';
export default function Pricing07({ components = [], sectionId = null }) {
  const defaultComponents = [
    { id: 'prc7-badge', type: 'badge', props: { content: 'Harga', background: '#052e16', color: '#4ade80' } },
    { id: 'prc7-heading', type: 'heading', props: { content: 'Paket Harga Transparan', level: 'h2', fontSize: '40px', fontWeight: '800', color: '#e2e8f0', align: 'center', margin: '0 0 12px 0' } },
    { id: 'prc7-text', type: 'text', props: { content: 'Pilih paket sesuai skala dan kebutuhan bisnis Anda.', fontSize: '15px', color: '#94a3b8', align: 'center', margin: '0 0 20px 0' } },
    { id: 'prc7-cta', type: 'button', props: { label: 'Konsultasi Gratis', href: '#konsultasi', variant: 'ghost', size: 'medium', background: 'transparent', color: '#e2e8f0' } },
    { id: 'prc7-card-1', type: 'card', props: { variant: 'pricing', background: '#0f172a', borderRadius: '24px', shadow: 'md', borderWidth: '1px', borderColor: '#1e293b', hoverEffect: 'lift', padding: '32px' }, childrenComponents: [ { id: 'prc7-c1-badge', type: 'badge', props: { content: 'STARTER', background: '#052e16', color: '#4ade80' } }, { id: 'prc7-c1-title', type: 'heading', props: { content: 'Paket UMKM', level: 'h3', fontSize: '20px', fontWeight: '700', color: '#e2e8f0', margin: '12px 0 4px 0' } }, { id: 'prc7-c1-price', type: 'heading', props: { content: 'Rp 2.500.000', level: 'h2', fontSize: '32px', fontWeight: '800', color: '#e2e8f0', margin: '8px 0 16px 0' } }, { id: 'prc7-c1-desc', type: 'text', props: { content: 'Website Profil Standar, Domain .ID, Hosting 1 Tahun, Support WhatsApp', fontSize: '14px', color: '#94a3b8', margin: '0 0 24px 0' } }, { id: 'prc7-c1-btn', type: 'button', props: { label: 'Pilih Paket', href: '#harga', variant: 'primary', size: 'medium', radius: 'full', background: '#22c55e', color: '#052e16' } } ] },
    { id: 'prc7-card-2', type: 'card', props: { variant: 'pricing', background: '#0f172a', borderRadius: '24px', shadow: 'md', borderWidth: '1px', borderColor: '#1e293b', hoverEffect: 'lift', padding: '32px' }, childrenComponents: [ { id: 'prc7-c2-badge', type: 'badge', props: { content: 'POPULER', background: '#052e16', color: '#4ade80' } }, { id: 'prc7-c2-title', type: 'heading', props: { content: 'Paket Profesional', level: 'h3', fontSize: '20px', fontWeight: '700', color: '#e2e8f0', margin: '12px 0 4px 0' } }, { id: 'prc7-c2-price', type: 'heading', props: { content: 'Rp 5.000.000', level: 'h2', fontSize: '32px', fontWeight: '800', color: '#e2e8f0', margin: '8px 0 16px 0' } }, { id: 'prc7-c2-desc', type: 'text', props: { content: 'Custom Multi-Template, SEO Optimization, Payment Gateway, Priority 24/7', fontSize: '14px', color: '#94a3b8', margin: '0 0 24px 0' } }, { id: 'prc7-c2-btn', type: 'button', props: { label: 'Pilih Paket', href: '#harga', variant: 'primary', size: 'medium', radius: 'full', background: '#22c55e', color: '#052e16' } } ] },
    { id: 'prc7-card-3', type: 'card', props: { variant: 'pricing', background: '#0f172a', borderRadius: '24px', shadow: 'md', borderWidth: '1px', borderColor: '#1e293b', hoverEffect: 'lift', padding: '32px' }, childrenComponents: [ { id: 'prc7-c3-badge', type: 'badge', props: { content: 'ENTERPRISE', background: '#052e16', color: '#4ade80' } }, { id: 'prc7-c3-title', type: 'heading', props: { content: 'Paket Perusahaan', level: 'h3', fontSize: '20px', fontWeight: '700', color: '#e2e8f0', margin: '12px 0 4px 0' } }, { id: 'prc7-c3-price', type: 'heading', props: { content: 'Custom', level: 'h2', fontSize: '32px', fontWeight: '800', color: '#e2e8f0', margin: '8px 0 16px 0' } }, { id: 'prc7-c3-desc', type: 'text', props: { content: 'Sistem Enterprise, Dedicated Server, SLA 99.9%, Account Manager', fontSize: '14px', color: '#94a3b8', margin: '0 0 24px 0' } }, { id: 'prc7-c3-btn', type: 'button', props: { label: 'Pilih Paket', href: '#harga', variant: 'primary', size: 'medium', radius: 'full', background: '#22c55e', color: '#052e16' } } ] },
  ];
  const layoutComponents = components.length > 0 ? components : defaultComponents;
  const header = layoutComponents.filter((c) => c.type !== 'card');
  const cards = layoutComponents.filter((c) => c.type === 'card');
  return ( <section className="py-20 px-6 bg-[#020617] font-mono"> <div className="flex items-center gap-1.5 mb-6 select-none pointer-events-none"><span className="w-3 h-3 rounded-full bg-red-500" /><span className="w-3 h-3 rounded-full bg-yellow-500" /><span className="w-3 h-3 rounded-full bg-green-500" /></div> <div className="relative max-w-6xl mx-auto flex flex-col items-center text-center"> {renderLayoutComponents(header.filter((c) => c.type === 'badge'), sectionId)} <div className="mt-4 w-full">{renderLayoutComponents(header.filter((c) => c.type === 'heading'), sectionId)}</div> <div className="max-w-2xl">{renderLayoutComponents(header.filter((c) => c.type === 'text'), sectionId)}</div> <div className="mt-1">{renderLayoutComponents(header.filter((c) => c.type === 'button'), sectionId)}</div> <div className="grid grid-cols-1 md:grid-cols-3 gap-6 w-full mt-10 text-left"> {renderLayoutComponents(cards, sectionId)} </div> </div> </section> );
}
