import { renderLayoutComponents } from '../../../engine/layoutRenderer.jsx';
export default function Pricing08({ components = [], sectionId = null }) {
  const defaultComponents = [
    { id: 'prc8-badge', type: 'badge', props: { content: 'Harga', background: '#fce7f3', color: '#be185d' } },
    { id: 'prc8-heading', type: 'heading', props: { content: 'Paket Harga Transparan', level: 'h2', fontSize: '40px', fontWeight: '800', color: '#831843', align: 'center', margin: '0 0 12px 0' } },
    { id: 'prc8-text', type: 'text', props: { content: 'Pilih paket sesuai skala dan kebutuhan bisnis Anda.', fontSize: '15px', color: '#9d7b8c', align: 'center', margin: '0 0 20px 0' } },
    { id: 'prc8-cta', type: 'button', props: { label: 'Konsultasi Gratis', href: '#konsultasi', variant: 'ghost', size: 'medium', background: 'transparent', color: '#831843' } },
    { id: 'prc8-card-1', type: 'card', props: { variant: 'pricing', background: '#fff1f2', borderRadius: '24px', shadow: 'md', borderWidth: '1px', borderColor: '#fff1f2', hoverEffect: 'lift', padding: '32px' }, childrenComponents: [ { id: 'prc8-c1-badge', type: 'badge', props: { content: 'STARTER', background: '#fce7f3', color: '#be185d' } }, { id: 'prc8-c1-title', type: 'heading', props: { content: 'Paket UMKM', level: 'h3', fontSize: '20px', fontWeight: '700', color: '#831843', margin: '12px 0 4px 0' } }, { id: 'prc8-c1-price', type: 'heading', props: { content: 'Rp 2.500.000', level: 'h2', fontSize: '32px', fontWeight: '800', color: '#831843', margin: '8px 0 16px 0' } }, { id: 'prc8-c1-desc', type: 'text', props: { content: 'Website Profil Standar, Domain .ID, Hosting 1 Tahun, Support WhatsApp', fontSize: '14px', color: '#9d7b8c', margin: '0 0 24px 0' } }, { id: 'prc8-c1-btn', type: 'button', props: { label: 'Pilih Paket', href: '#harga', variant: 'primary', size: 'medium', radius: 'full', background: '#db2777', color: '#ffffff' } } ] },
    { id: 'prc8-card-2', type: 'card', props: { variant: 'pricing', background: '#fff1f2', borderRadius: '24px', shadow: 'md', borderWidth: '1px', borderColor: '#fff1f2', hoverEffect: 'lift', padding: '32px' }, childrenComponents: [ { id: 'prc8-c2-badge', type: 'badge', props: { content: 'POPULER', background: '#fce7f3', color: '#be185d' } }, { id: 'prc8-c2-title', type: 'heading', props: { content: 'Paket Profesional', level: 'h3', fontSize: '20px', fontWeight: '700', color: '#831843', margin: '12px 0 4px 0' } }, { id: 'prc8-c2-price', type: 'heading', props: { content: 'Rp 5.000.000', level: 'h2', fontSize: '32px', fontWeight: '800', color: '#831843', margin: '8px 0 16px 0' } }, { id: 'prc8-c2-desc', type: 'text', props: { content: 'Custom Multi-Template, SEO Optimization, Payment Gateway, Priority 24/7', fontSize: '14px', color: '#9d7b8c', margin: '0 0 24px 0' } }, { id: 'prc8-c2-btn', type: 'button', props: { label: 'Pilih Paket', href: '#harga', variant: 'primary', size: 'medium', radius: 'full', background: '#db2777', color: '#ffffff' } } ] },
    { id: 'prc8-card-3', type: 'card', props: { variant: 'pricing', background: '#fff1f2', borderRadius: '24px', shadow: 'md', borderWidth: '1px', borderColor: '#fff1f2', hoverEffect: 'lift', padding: '32px' }, childrenComponents: [ { id: 'prc8-c3-badge', type: 'badge', props: { content: 'ENTERPRISE', background: '#fce7f3', color: '#be185d' } }, { id: 'prc8-c3-title', type: 'heading', props: { content: 'Paket Perusahaan', level: 'h3', fontSize: '20px', fontWeight: '700', color: '#831843', margin: '12px 0 4px 0' } }, { id: 'prc8-c3-price', type: 'heading', props: { content: 'Custom', level: 'h2', fontSize: '32px', fontWeight: '800', color: '#831843', margin: '8px 0 16px 0' } }, { id: 'prc8-c3-desc', type: 'text', props: { content: 'Sistem Enterprise, Dedicated Server, SLA 99.9%, Account Manager', fontSize: '14px', color: '#9d7b8c', margin: '0 0 24px 0' } }, { id: 'prc8-c3-btn', type: 'button', props: { label: 'Pilih Paket', href: '#harga', variant: 'primary', size: 'medium', radius: 'full', background: '#db2777', color: '#ffffff' } } ] },
  ];
  const layoutComponents = components.length > 0 ? components : defaultComponents;
  const header = layoutComponents.filter((c) => c.type !== 'card');
  const cards = layoutComponents.filter((c) => c.type === 'card');
  return ( <section className="py-24 px-6 bg-gradient-to-b from-pink-50 to-white"> <div className="flex items-center justify-center gap-2 my-1 select-none pointer-events-none"><div className="w-12 h-px bg-pink-300" /><span className="text-pink-400">✦</span><div className="w-12 h-px bg-pink-300" /></div> <div className="relative max-w-6xl mx-auto flex flex-col items-center text-center"> {renderLayoutComponents(header.filter((c) => c.type === 'badge'), sectionId)} <div className="mt-4 w-full">{renderLayoutComponents(header.filter((c) => c.type === 'heading'), sectionId)}</div> <div className="max-w-2xl">{renderLayoutComponents(header.filter((c) => c.type === 'text'), sectionId)}</div> <div className="mt-1">{renderLayoutComponents(header.filter((c) => c.type === 'button'), sectionId)}</div> <div className="grid grid-cols-1 md:grid-cols-3 gap-6 w-full mt-10 text-left"> {renderLayoutComponents(cards, sectionId)} </div> </div> </section> );
}
