import { renderLayoutComponents } from '../../../engine/layoutRenderer.jsx';
export default function Pricing19({ components = [], sectionId = null }) {
  const defaultComponents = [
    { id: 'prc19-badge', type: 'badge', props: { content: 'Harga', background: '#eef2ff', color: '#4f46e5' } },
    { id: 'prc19-heading', type: 'heading', props: { content: 'Paket Harga Transparan', level: 'h2', fontSize: '40px', fontWeight: '800', color: '#0f172a', align: 'center', margin: '0 0 12px 0' } },
    { id: 'prc19-text', type: 'text', props: { content: 'Pilih paket sesuai skala dan kebutuhan bisnis Anda.', fontSize: '15px', color: '#64748b', align: 'center', margin: '0 0 20px 0' } },
    { id: 'prc19-cta', type: 'button', props: { label: 'Konsultasi Gratis', href: '#konsultasi', variant: 'ghost', size: 'medium', background: 'transparent', color: '#0f172a' } },
    { id: 'prc19-card-1', type: 'card', props: { variant: 'pricing', background: 'rgba(255,255,255,0.85)', borderRadius: '24px', shadow: 'md', borderWidth: '1px', borderColor: '#ffffff', hoverEffect: 'lift', padding: '32px' }, childrenComponents: [ { id: 'prc19-c1-badge', type: 'badge', props: { content: 'STARTER', background: '#eef2ff', color: '#4f46e5' } }, { id: 'prc19-c1-title', type: 'heading', props: { content: 'Paket UMKM', level: 'h3', fontSize: '20px', fontWeight: '700', color: '#0f172a', margin: '12px 0 4px 0' } }, { id: 'prc19-c1-price', type: 'heading', props: { content: 'Rp 2.500.000', level: 'h2', fontSize: '32px', fontWeight: '800', color: '#0f172a', margin: '8px 0 16px 0' } }, { id: 'prc19-c1-desc', type: 'text', props: { content: 'Website Profil Standar, Domain .ID, Hosting 1 Tahun, Support WhatsApp', fontSize: '14px', color: '#64748b', margin: '0 0 24px 0' } }, { id: 'prc19-c1-btn', type: 'button', props: { label: 'Pilih Paket', href: '#harga', variant: 'primary', size: 'medium', radius: 'full', background: '#0f172a', color: '#ffffff' } } ] },
    { id: 'prc19-card-2', type: 'card', props: { variant: 'pricing', background: 'rgba(255,255,255,0.85)', borderRadius: '24px', shadow: 'md', borderWidth: '1px', borderColor: '#ffffff', hoverEffect: 'lift', padding: '32px' }, childrenComponents: [ { id: 'prc19-c2-badge', type: 'badge', props: { content: 'POPULER', background: '#eef2ff', color: '#4f46e5' } }, { id: 'prc19-c2-title', type: 'heading', props: { content: 'Paket Profesional', level: 'h3', fontSize: '20px', fontWeight: '700', color: '#0f172a', margin: '12px 0 4px 0' } }, { id: 'prc19-c2-price', type: 'heading', props: { content: 'Rp 5.000.000', level: 'h2', fontSize: '32px', fontWeight: '800', color: '#0f172a', margin: '8px 0 16px 0' } }, { id: 'prc19-c2-desc', type: 'text', props: { content: 'Custom Multi-Template, SEO Optimization, Payment Gateway, Priority 24/7', fontSize: '14px', color: '#64748b', margin: '0 0 24px 0' } }, { id: 'prc19-c2-btn', type: 'button', props: { label: 'Pilih Paket', href: '#harga', variant: 'primary', size: 'medium', radius: 'full', background: '#0f172a', color: '#ffffff' } } ] },
    { id: 'prc19-card-3', type: 'card', props: { variant: 'pricing', background: 'rgba(255,255,255,0.85)', borderRadius: '24px', shadow: 'md', borderWidth: '1px', borderColor: '#ffffff', hoverEffect: 'lift', padding: '32px' }, childrenComponents: [ { id: 'prc19-c3-badge', type: 'badge', props: { content: 'ENTERPRISE', background: '#eef2ff', color: '#4f46e5' } }, { id: 'prc19-c3-title', type: 'heading', props: { content: 'Paket Perusahaan', level: 'h3', fontSize: '20px', fontWeight: '700', color: '#0f172a', margin: '12px 0 4px 0' } }, { id: 'prc19-c3-price', type: 'heading', props: { content: 'Custom', level: 'h2', fontSize: '32px', fontWeight: '800', color: '#0f172a', margin: '8px 0 16px 0' } }, { id: 'prc19-c3-desc', type: 'text', props: { content: 'Sistem Enterprise, Dedicated Server, SLA 99.9%, Account Manager', fontSize: '14px', color: '#64748b', margin: '0 0 24px 0' } }, { id: 'prc19-c3-btn', type: 'button', props: { label: 'Pilih Paket', href: '#harga', variant: 'primary', size: 'medium', radius: 'full', background: '#0f172a', color: '#ffffff' } } ] },
  ];
  const layoutComponents = components.length > 0 ? components : defaultComponents;
  const header = layoutComponents.filter((c) => c.type !== 'card');
  const cards = layoutComponents.filter((c) => c.type === 'card');
  return ( <section className="py-20 px-6 bg-slate-50">  <div className="relative max-w-6xl mx-auto flex flex-col items-center text-center"> {renderLayoutComponents(header.filter((c) => c.type === 'badge'), sectionId)} <div className="mt-4 w-full">{renderLayoutComponents(header.filter((c) => c.type === 'heading'), sectionId)}</div> <div className="max-w-2xl">{renderLayoutComponents(header.filter((c) => c.type === 'text'), sectionId)}</div> <div className="mt-1">{renderLayoutComponents(header.filter((c) => c.type === 'button'), sectionId)}</div> <div className="grid grid-cols-1 md:grid-cols-3 gap-6 w-full mt-10 text-left"> {renderLayoutComponents(cards, sectionId)} </div> </div> </section> );
}
